---

dataset:
  max_samples: null
  n_classes: 10
  test_path: ./data/mnist/test/
  train_path: ./data/mnist/train/

implicit:
  fwd_solver: lbfgs
  fwd_iterations: 100
  fwd_init: random

  bwd_solver: neumann
  bwd_iterations: 3

  anderson_m: 5
  anderson_b: 0.9

model:
  n_channels: 12
  kernel_size: 3
  key: 0

optimizer:
  learning_rate: 1e-3
  name: adamw

trainer:
  batch_size: 16
  eval_freq: 100
  eval_iters: 5
  key: 0
  lambda_reg: 0.1
  total_iters: 100_000

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
