---

dataset:
  max_samples: null
  n_classes: 10
  test_path: ./data/mnist/test/
  train_path: ./data/mnist/train/

implicit:
  name: "anderson"
  n_iterations: 50
  anderson_m: 3
  anderson_b: 0.9

model:
  n_channels: 12
  kernel_size: 3
  key: 0

optimizer:
  learning_rate: 1e-2
  name: adamw

trainer:
  batch_size: 32
  eval_freq: 100
  eval_iters: 5
  lambda_reg: 0.01
  key: 0
  total_iters: 10_000

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
