---

dataset:
  max_samples: null
  n_classes: 10
  test_path: ./data/mnist/test/
  train_path: ./data/mnist/train/

model:
  n_channels: 24
  kernel_size: 3
  key: 0

optimizer:
  learning_rate: 1e-4
  name: adamw

trainer:
  batch_size: 16
  eval_freq: 100
  eval_iters: 10
  key: 0
  total_iters: 10_000

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
