---

dataset:
  max_samples: 10
  n_classes: 10
  test_path: ./data/mnist/test/
  train_path: ./data/mnist/train/

implicit:
  solve_method: anderson
  tangent_solve_method: anderson

model:
  n_channels: 12
  kernel_size: 3
  key: 0

optimizer:
  learning_rate: 1e-2
  name: adamw

trainer:
  batch_size: 4
  eval_freq: 100
  eval_iters: 4
  gamma: 0.01
  key: 0
  total_iters: 10_000

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
